Storage pmd11
lanl-ansi/PowerModelsProtection.jl pull request #35
Opened 2021-08-10 14:12 UTC by jtabarez

The storage constraints are added to the gfmi constraints and the storage constraints will only focus on energy.

2021-08-10 15:00 UTC, pseudocubic requested changes
For docstrings, I suggest the following format to match PowerModelsDistribution's docstring format conventions:

```julia
@doc raw"""
    <function_name>(<args>; <kwargs>...)::<return_type>

<Description of function>

<math_if_applicable>
"""
```

That is for exported functions. For private functions (those starting with `_`), just a single line description will suffice. the `@doc raw"""` part is only needed if you are using LaTeX math, because of escape characters

2021-09-19 16:17 UTC, bluejuniper commented on src/core/constraint_inverter.jl
> +    JuMP.@NLconstraint(pm.model, sum(vr[c]*crs[c] + vi[c]*cis[c] for c in connections) == p)
This is actually a bilinear constraint. I assume that `@NLconstraint` is needed in this case?

2021-09-19 16:47 UTC, bluejuniper commented on Project.toml
> +Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
Checked and we are not using Juniper - it's removed from deps & extras

2021-09-19 16:51 UTC, bluejuniper commented on src/core/constraint_inverter.jl
> +function constraint_mc_storage_grid_forming_inverter(pm::_PMD.AbstractUnbalancedIVRModel, nw::Int, i, bus_id, vr0, vi0, pmax, qmax, qmin, cmax, smax, energy, energy_rating, ang, connections)
The unused arguments were left over from before the inverter-only constraints from `constraint_mc_storage_grid_forming_inverter` were split out into `constraint_mc_grid_forming_inverter`. Removed

2021-09-20 13:29 UTC, bluejuniper commented on src/core/variable.jl
> +    connections = Dict(i => storage["connections"] for (i,storage) in _PMD.ref(pm, nw, :storage))
If I'm following correctly the `bus_conns_storage` dictionary provides a list of tuples for each BESS at a bus so it's not exactly the data structure we are using

2021-09-20 13:40 UTC, pseudocubic commented on src/core/constraint_inverter.jl
> +    JuMP.@NLconstraint(pm.model, sum(vr[c]*crs[c] + vi[c]*cis[c] for c in connections) == p)
I'm pretty sure quadratic and bilinear constraints can still use `@constraint`, and don't require `@NLconstraint`

2021-09-20 15:16 UTC, bluejuniper commented on src/core/constraint_template.jl
> +    haskey(storage, "i_max") ? nothing : storage["i_max"] = 1.1*storage["dss"]["kva"] / (3 * 100 * baseMVA)
Removed this as it's no longer being used anyways

2021-09-20 16:05 UTC, bluejuniper approved these changes
Finishing going through David's comments and added some more unit tests. Tests are passing

2021-09-23 20:20 UTC, pseudocubic commented on Project.toml
> +Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
It seems to still be appearing in the latest changes

2021-09-23 20:26 UTC, pseudocubic commented
There is still one issue from the code comments (Juniper still appears in deps in the project.toml), I think you're missing an updated changelog, and I still recommend going through and updating the docstrings to the suggested format, at least for the new functions you added. 

other than that all the other issues seem resolved.

2021-09-28 20:44 UTC, pseudocubic approved these changes

2021-09-28 21:36 UTC, merged